### PR TITLE
Milestone 4: Styling

### PR DESCRIPTION
**Pull request by jaflih**
### Milestone 4: Styling

Add Styling
Capture d’écran 2022-02-23 à 17 03 59

### CODE REVIEW

**Review by Lameck1 — APPROVED** [review]
Hi, @jaflih, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

# Highlights
- Professional README ✔️
- Clean code ✔️ 
- Good commit messages ✔️ 
- Beautiful UI styling ✔️ 

## Required Changes ♻️
- [ ] When that app is started this bug pops up: 
  
  image
  
  This is because you intended to use `react-icons` but this package is not available in the project's `package.json`. Please add this package by running:
  
  ```
  npm install react-icons --save
  ```
  
  This will ensure the project runs. Besides this, the rest should be good.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, remember to tag me in your question so I can receive the notification.**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jaflih** [comment]
Hi @Lameck1 ! 

Thank you for the review, you're right I forgot to push the new package.json.
I fixed it.

**Review by elyor-doniyorov — APPROVED** [review]
Hi @jaflih, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS APPROVED ✅ 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jaflih** [comment]
Hi @elyor-doniyorov Thank you,
thankyou

**Pull request merged**
